import { StyleSheet } from 'react-native';
import { colors, radius, shadow, MAX_CONTENT_WIDTH } from '../theme/theme';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  scroll: {
    width: '100%',
    maxWidth: MAX_CONTENT_WIDTH,
    alignSelf: 'center',
    padding: 18,
    paddingBottom: 40,
  },
  profileTop: {
    alignItems: 'center',
    backgroundColor: colors.surface,
    borderRadius: radius.lg,
    paddingVertical: 24,
    paddingHorizontal: 16,
    marginBottom: 22,
    ...shadow(3),
  },
  avatar: {
    width: 92,
    height: 92,
    borderRadius: 46,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
  },
  avatarText: {
    fontSize: 38,
    color: colors.white,
    fontWeight: '800',
  },
  profileInfo: {
    alignSelf: 'stretch',
    alignItems: 'center',
  },
  nameRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  name: {
    flexShrink: 1,
    fontSize: 22,
    fontWeight: '800',
    color: colors.text,
  },
  editNameBtn: {
    marginLeft: 6,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primaryLight,
    justifyContent: 'center',
    alignItems: 'center',
  },
  nameEditor: {
    alignSelf: 'stretch',
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  nameInput: {
    flex: 1,
    marginBottom: 0,
  },
  nameEditorBtn: {
    width: 52,
    height: 52,
    borderRadius: radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 6,
  },
  email: {
    fontSize: 15,
    color: colors.textSecondary,
    marginTop: 4,
  },
  sectionLabel: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.text,
    marginBottom: 10,
    marginLeft: 4,
  },
  statsRow: {
    flexDirection: 'row',
    marginHorizontal: -5,
    marginBottom: 22,
  },
  statCard: {
    flex: 1,
    borderRadius: radius.lg,
    paddingVertical: 14,
    alignItems: 'center',
    marginHorizontal: 5,
  },
  statValue: {
    fontSize: 26,
    fontWeight: '800',
    marginTop: 4,
  },
  statLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSecondary,
    marginTop: 2,
  },
  apiSection: {
    padding: 20,
    borderRadius: radius.lg,
    marginBottom: 24,
  },
  apiHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  apiTitle: {
    fontSize: 15,
    fontWeight: '800',
    color: colors.white,
  },
  offlineBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderRadius: radius.pill,
    paddingVertical: 3,
    paddingHorizontal: 8,
  },
  offlineText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.white,
    marginLeft: 4,
  },
  quoteText: {
    fontSize: 18,
    fontWeight: '600',
    color: colors.white,
    lineHeight: 26,
    marginBottom: 8,
  },
  quoteAuthor: {
    fontSize: 14,
    color: 'rgba(255,255,255,0.85)',
  },
  quoteLoading: {
    marginVertical: 20,
  },
  refreshBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    alignSelf: 'flex-start',
    backgroundColor: colors.white,
    borderRadius: radius.pill,
    paddingVertical: 8,
    paddingHorizontal: 14,
    marginTop: 16,
  },
  refreshBtnText: {
    color: colors.primary,
    fontWeight: '800',
    fontSize: 14,
    marginLeft: 4,
  },
  actionSpacing: {
    marginBottom: 12,
  },
});
